### PR TITLE
v1.0.0 merge

### PR DESCRIPTION
**Pull request by roddymunro**

### CODE REVIEW

**Comment by petrusck** [comment]
I fixed almost all SwiftFormat issues in #19, you can take a look at it

**Comment by roddymunro** [comment]
Weird that this passed on #20 ! Taking a look

Edit: Fixed :)

**Comment by petrusck** [comment]
I modified the custom methods on XCTest for asserting on async throwing expressions to avoid disabling the `hoistAwait` rule of SwiftFormat in #22, you can take a look at it

**Comment by roddymunro** [comment]
@pereBohigas I'll be looking to merge this as soon as next week and release version 1.0!

**Pull request merged**
